magfest/sideboard

.gitignore
pavement.py

install_deps() now uses pip to install stuff, instead of setuptools
needed for docker
removes an extra step when using puppet
@EliAndrewC need your eyes on this for merge.  afterwards I have a bunch of other PR's that change the sideboard branch back to master
This PR should be merged --first--

use pip to install requirements by default

---

sideboard/internal/imports.py

In some cases, Sideboard was comparing a full path (e.g. '/home/vagrant/uber/sideboard/plugins/uber') with a plugin name (e.g. 'uber') to sort plugins. Doing so would break priority plugins settings. This now always uses the 'basename' of a directory, so you don't have to worry about its path.
Fixes https://github.com/magfest/sideboard/issues/13.

Make priority_plugins work regardless of setup vagaries

---

sideboard/internal/imports.py

Since glob() returns an ordering that is os-dependent, we need to sort here in order to ensure that all OS'es load the non-prioritized plugins in the same order
This change does not fix any loading issues, BUT it will ensure that if there IS a load order issue, it will happen either everywhere or nowhere.  This eliminates "why is it working on my machine but not on the server".
sidenote: Originally I wanted to do this change as a precaution, however, it turns out it's necessary for my computer and magstock staging server to load things in the same order.
non-prioritized plugin load order on magfest staging server:
```
['bands', 'barcode', 'magstock', 'uber_analytics']
```
non-prioritized plugin load order on my box:
```
['magstock', 'barcode', 'uber_analytics', 'bands']
```
both …

sort glob() output for consistent results

---

development-defaults.ini
sideboard/internal/logging.py

2 things:
1) Add a formatter (which is off by default but can be switched on via INI) that takes any multiline output and indents it.  This makes it easier for external log tools to parse our output and keep stack traces (which output multiple lines) together as one logical unit.
2) By default we output to syslog via development-defaults.ini and downstream configuration can't switch this off.  Make it so we don't output to syslog by default so that puppet and other things can change this behavior later

Centralized logging - add multiline indent, remove syslog output by default

---

sideboard/configspec.ini

- doesn't add much spam but does report which files are actually being served up, which is good data to collect
definitely want this on our servers in order to get the access logs, but also, I think it's a sensible default even if it adds a line for each access.

turn up all logging thresholds to the highest levels

---

sideboard/lib/_threads.py

this is useful to add a more descriptive name to be shown to the OS, and to work around 16 char OS thread name limits

add override for thread names for DaemonTasks

---

.travis.yml
requirements.txt
setup.py
sideboard/lib/_threads.py

- this code monkeypatches the start of each thread to call prctl() which sets the thread name
- this allows external utilities, like top and ps, to show thread names
- this is great because if a particular thread is going off the rails, we can now see which one using external tools
- requires build-package and libcap to be installed on the system
requires https://github.com/magfest/ubersystem-puppet/pull/110

set thread names on startup

---

requirements.txt

- turns out this is needed for pycharm
- and is a decent idea to do this anyway

upgrade pytest to latest version

---

setup.cfg

apparently the old way is deprecated

use new format for setup.cfg so pytest stops complaining

---

sideboard/lib/__init__.py
sideboard/lib/_utils.py
sideboard/tests/test_lib.py

This feature has come up as something that would be useful both at my day job and in some of the MAGFest background tasks.
We want a lock with the following characteristics:
- any number of threads may acquire the lock in "read mode"
- only one thread may have the lock acquired in "write mode" at a time
- the locking modes are reentrant, i.e. the same thing can acquire the lock multiple times
- writes take precedence over reads, e.g. once a writer requests the lock, subsequent readers will block until the writer acquires and releases the lock
Locks are hard to write good unit tests for.  I did add several unit tests for this feature, including one which spins up other threads to ensure that the locking works as expected.  However, in order to REALLY test this out, I also wrote this …

implemented a read/write lock utility class in sideboard.lib

---

sideboard/config.py
sideboard/internal/logging.py
sideboard/tests/test_configuration.py

We implemented this locally to make it easier to run unit tests on different environments.  I accidentally neglected to push this up with my recent "resync back to the public repo" work.
This is relevant to https://github.com/magfest/sideboard/issues/66 which I'll comment on in a second to explain how it relates to what's been proposed there.

added SIDEBOARD_CONFIG_ROOT environment variable

---

sideboard/lib/sa/__init__.py
sideboard/tests/test_sa.py

If you have any unnamed ~constraints – even non CheckConstraints –~ unnamed CheckConstraints SQLAlchemy will complain if you try to use the `%(constraint_name)s` token in MetaData.naming_conventions. So, instead of using `%(constraint_name)s` as suggested [in the docs](http://docs.sqlalchemy.org/en/latest/core/constraints.html#constraint-naming-conventions), I'm adding a custom function that converts the CheckConstraint.sqltext to a valid name.
It's not used anywhere in sideboard directly, but it's a generally useful function that many plugins can use.

Adds custom unnamed CheckedConstraint naming convention to support Alembic migrations

---

sideboard/internal/imports.py
sideboard/tests/test_imports.py

The plugin import order will be useful for generating/running DB migrations. Plus it's just a generally useful thing to have around. The heart of this pull request was swapping `plugins = {}` with `plugins = OrderedDict()`, but I did some additional code refactoring to make it easier to test.
I'll add some review comments explaining my thinking.

Preserves plugin import order using OrderedDict

---

sideboard/internal/imports.py

Populates plugin_dirs before importing plugins, so it will be available to plugins that depend on plugin_dirs. Also, it just seems like a good idea to separate these.

Populates plugin_dirs before importing plugins

---

Dockerfile

Upstream needs to sync up with MAGFest's sideboard. Even if this isn't merged, we need it to create a mergeable PR.

Add Dockerfile from upstream

---

.gitignore
sideboard/configspec.ini
sideboard/lib/__init__.py
sideboard/lib/_profiler.py
sideboard/server.py
sideboard/tests/test_configuration.py
sideboard/tests/test_profiler.py
test-defaults.ini
tox.ini

This is based on the built-in cherrypy profiler, but with some improvements.
The web UI looks like this:

Adds profiling tools and exposes profiler web UI

---

.travis.yml
sideboard/lib/_profiler.py
sideboard/tests/test_imports.py
sideboard/tests/test_profiler.py

MAGFest uses Python 3 and so doesn't care about ``from __future__ import unicode_literals`` but at my day job we still use Python 2.7 for a couple of legacy codebases and so we have our local builds check for the presence of that line in every Python file in the Sideboard codebase.  I've added it in to a few new files where it was missing; I didn't think to check for it when I was reviewing those files since all of my new projects have been on Python 3 for some time.
I also removed the unnecessary Travis line we discussed in the other PR.

Adding missing unicode_literals imports

---

requirements.txt

Fixes #56. Looks like everything works on the latest version of cherrypy. The tests are passing and uber seems to be working fine (although we still have [this unrelated intermittent problem](https://github.com/magfest/sideboard/issues/76)).

Fixes #56: Removes upper bounds on cherrypy version requirement

---

sideboard/lib/_utils.py
sideboard/tests/test_lib.py

It's a very common convention in the python world to use `property_name` for a "public" property and `_property_name` for a "private" attribute. That's probably why this naming convention was chosen for `@cached_property` in the first place.
However, because it's so common, it's not unreasonable to expect collisions to happen when an unsuspecting programmer expects to be able to use both names.

Changes name used for cached property to avoid collisions with common naming pattern

---

sideboard/lib/sa/__init__.py

This particular line was absolutely hammering us when we're instantiating model objects from a persisted dictionary. When we ALREADY have the value for a column (because it was given as an argument), there's no need to calculate the default value of that column. We already know the value we want to use!
In this pull request, we are looking to see if a column value was given to us as an argument, and if so, we skip the default value calculation.

Avoids executing column defaults when they aren't needed

---

sideboard/lib/sa/__init__.py

This handles some cases that I didn't consider in this pull request: https://github.com/magfest/sideboard/pull/88

Only skip executing column defaults if the argument is None

---

sideboard/internal/autolog.py
sideboard/jsonrpc.py

The `jsonrpc_handler` was created with the intent that it would be added as a member of a class, so it was given a single positional parameter named `self`.  This unfortunately breaks when the `jsonrpc_handler` is used outside the context of a class (it throws "missing required `self` argument" errors).
The `self` parameter is never actually referenced. This pull request switches the parameter from `self` to `self=None`, so the `jsonrpc_handler` function can be invoked outside the context of a class.

Makes jsonrpc_handler more flexible

---

requirements.txt

looks like these were left off in a merge error, adding them back in
fixes #90 
I BELIEVE this was just a merge error but @EliAndrewC  and @RobRuana if you know of any reason why these shouldn't be here, let me know.
It's super-useful to see the thread names in htop when diagnosing CPU issues on production servers, and in the future once we have multiple processes going.

add psutil and prctl

---

requirements.txt
setup.py

Turns out, the `python-prctl` is only supported on linux.
Fortunately, `pip` supports super cool [Environment Markers](https://www.python.org/dev/peps/pep-0496/) in `requirements.txt` files!
```
python-prctl>=1.6.1; 'linux' in sys_platform
```
Unfortunately, `setup.py` `install_requires` does NOT understand Environment Markers :cry:
So I did a bad thing. I made an ugly hack to add basic Environment Marker support to our `setup.py`.

Adds basic support for pip environment markers to setup.py

---

docs/source/index.rst
sideboard/internal/imports.py
sideboard/lib/_cp.py

When trying to use celery to run tasks from a plugin (or any other non `sep` script), we encounter an import sequence that causes subsequent plugins to load _before_ the initial plugin is fully loaded. This causes errors if the subsequent plugins have dependencies on the initial plugin.
For example, consider the case where we have two plugins: `alpha` and `omega`, where `omega` depends on `alpha`. The top-level modules for each look like this:
```python
import sideboard
from alpha import config
from alpha import models
from alpha import site_sections
from alpha import tasks
```
```python
from alpha import config
config.function_we_expect_to_exist()
```
The following sequence will occur when we try to run `celery -A alpha.tasks worker`:
1. `alpha` starts being imported
2. Before `alpha` is …

Adds support for plugin.on_load() to plugin lifecycle.

---

sideboard/lib/_cp.py

*Note:* this does NOT require `redis` or `cherrys`, but it will use them if they are available. If a plugin wants to use redis based sessions, it's the plugin's responsibility to ensure `cherrys` is installed.

Adds support for redis based sessions

---

requirements.txt

Later versions of cherrypy have some backwards-incompatible changes which prevent Sideboard from working.  In the long run we should pin to a later version or above and fix these import incompatibilities, but for now we pin to this version to prevent the issue.

pinned cherrypy to version 17.3.0

---

Dockerfile

The version of Pillow we use requires at least Python 3.6.

Upgrade Python

---

sideboard/server.py

As far as I know this endpoint to access the API services is unused, and skips all authentication. I'm going to close it to avoid having unsuspecting admins accidentally leaving it exposed.

Close /wsrpc endpoint

---

requirements.txt
sideboard/lib/_cp.py
sideboard/lib/_redissession.py

There's no version of cherrys that supports our combination of redis+cherrypy, and it's trivial to fork. This pulls it in directly and fixes a couple bugs.

Drop usage of cherrys library

---

sideboard/server.py

This removes the built-in debug endpoints that sideboard hosts at `/` to make room for a default plugin to live there.

Clearing sideboard root paths
